### ISSUE TITLE
Add CVE scan

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/docker-asciidoctor#224]
As discussed in Zulip, we could add [azure/container-scan](https://github.com/Azure/container-scan) to obtain a report on CVEs included in the image.

Ideally, we want it to run on every build after `make build` which is simple when running in the same job since we are scaning the locally generated `asciidoctor:latest` image. However the issue is that if we find a HIGH CVE (which happens now*) the build will break and maybe that's not desirable.
If we don't want that, we can:
1. Have another job that runs make and scans on PRs. I assume the docker buildx engine should produce equivalent images. In case the scan jobs fails we can still proceed with release steps in `build`.
2. Same as 1, but manual job to avoid noise. I personally don't like this, I'd rather have an annoying reminder of CVEs that not.

\* The issue are jars pulled by `epubcheck-ruby:4.2.4.0` and indirect ruby dependencies. Upgrading to epubcheck-ruby latest v4.2.6.0 fixes the jar issues but I don't know the impact of that. For Ruby we may need to go deeper...
```
Ruby (gemspec)
==============
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 2, CRITICAL: 0)

+----------+------------------+----------+-------------------+---------------+---------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                 TITLE                 |
+----------+------------------+----------+-------------------+---------------+---------------------------------------+
| json     | CVE-2020-10663   | HIGH     | 1.8.6             | 2.3.0         | rubygem-json: Unsafe object           |
|          |                  |          |                   |               | creation vulnerability in JSON        |
|          |                  |          |                   |               | -->avd.aquasec.com/nvd/cve-2020-10663 |
+----------+------------------+          +-------------------+---------------+---------------------------------------+
| nokogiri | CVE-2021-41098   |          | 1.11.7            | 1.12.5        | rubygem-nokogiri: XEE on JRuby        |
|          |                  |          |                   |               | -->avd.aquasec.com/nvd/cve-2021-41098 |
+----------+------------------+----------+-------------------+---------------+---------------------------------------+
```

**Comment by abelsromero** [comment]
>     * Running a `make build` on a contributor machine should never require to create an account anywhere (Haven't look at the security scan tool you're mentioning, but some former tools in this area required an account to access vuln. databases)

It doesn't require anything. As far as I've seen it scans the files for specific files in a CVE database. That means that if I rename a known jar to something else it wont' match it. Also, the action is just a wrapper of https://github.com/aquasecurity/trivy which can be run as a plain CLI locally.


>     * It should not break the build if vulnerabilities are detected (at least not for the first iterations).

Then, it discards using it as part of the main build, but a failure will definetly happen. So if we want to reduce noise the only option is just ran as a weekly to scan latest version on dockerhub.


>     * Fixing the vulnerability might break a use case

The thing then is "can we trust the test?". For instance, 2 things to do are upgrading java to at least 11 and `epubcheck-ruby:4.2.4.0` but do the tests cover componentes that use those?

**Comment by abelsromero** [comment]
At it again, to go baby steps and avoid breaking things I like the idea of having a weekly scheduled job running on the latest release from dockerhub. If it helps to jump-start security fixing we can move to main build when we feel confortable.
So, I migrated my test pr to the official trivy github action and ended with a very simple config (runs [here](https://github.com/abelsromero/docker-asciidoctor/actions/workflows/cve-scan.yml)).

```
name: "CVE Scan"
on:
  workflow_dispatch: { }
  schedule:
    - cron: '0 9 * * 1'
jobs:
  scan-images:
    name: Scan latest public image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ docker-asciidoctor ]
        tag: [ latest ]
    steps:
      - name: Pull
        run: docker pull asciidoctor/${{ matrix.image }}:${{ matrix.tag }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/asciidoctor/${{ matrix.image }}:${{ matrix.tag }}'
          severity: 'CRITICAL,HIGH'
          format: 'table'
          # we can set to 0 to avoid breaking the pipeline
          exit-code: '1'
```

wdyt?
